feat: adds optional geoemtry extent shift
terrestris/react-geo pull request #3715
Opened 2024-01-10 09:31 UTC by mholthausen

## Description

This PR adjusts the `SearchResultPanel` with an optional property (`extentShift`) to apply  an offset to the features extent of an entry in the search results. This can be used when the map is overlaid by elements and the map center is no longer the actual map center at that moment.

@terrestris/devs please review

## Pull request type

- [ ] Bugfix
- [x] Feature
- [ ] Dependency updates
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe)

## Do you introduce a breaking change?

- [ ] Yes
- [x] No

## Checklist

- [x] I understand and agree that the changes in this PR will be licensed under the
  [BSD-2-Clause](https://github.com/terrestris/react-geo/blob/main/LICENSE).
- [x] I have followed the [guidelines for contributing](https://github.com/terrestris/react-geo/blob/main/CONTRIBUTING.md).
- [x] The proposed change fits to the content of the [Code of Conduct](https://github.com/terrestris/react-geo/blob/main/CODE_OF_CONDUCT.md).
- [x] I have added or updated tests and documentation, and the test suite passes (run `npm test` locally).
- [ ] I have added a screenshot/screencast to illustrate the visual output of my update.

2024-01-10 09:39 UTC, KaiVolland commented
Wouldn't it be better to add an `onClick` property which zooms to the feature by default and can then be overwritten? This looks like a quite specific requirement.

2024-01-10 09:49 UTC, mholthausen commented
Yes its specific requirement that was used in another project before and should be ported to the `SearchResultPanel` now so that it can be used by the gis client.

2024-01-10 09:54 UTC, KaiVolland requested changes
I added some suggestions to make clearer what i meant. (Code is not tested.)

This way you keep the project specific logic outside of this library *and* you make it even more flexible for other projects.

2024-01-10 09:56 UTC, dnlkoch requested changes
I agree with @KaiVolland here. Please make the `onClick` prop configurable to it can be adjusted to whatever an application might need.

2024-01-10 10:37 UTC, mholthausen commented
Okay, added a configurable `onClick` property in this component in [62a40c4](https://github.com/terrestris/react-geo/pull/3715/commits/62a40c469f7816be5b8af8b261e29da24ae6636c) with the previous behavior which can be overwritten.

2024-01-10 15:38 UTC, KaiVolland approved these changes
nice. thanks for the adjustments.

2024-01-11 07:05 UTC, mholthausen commented
:+1: thanks for the reviews!

2024-01-11 07:05 UTC, merged

2024-01-11 07:10 UTC, dnlkoch commented
:tada: This PR is included in version 23.3.0 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/@terrestris/react-geo/v/23.3.0)
- [GitHub release](https://github.com/terrestris/react-geo/releases/tag/v23.3.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: